"""
Validate Module - JSON Schema validation for workflow state

Validates that specified state keys conform to a JSON Schema.
Used primarily by execution groups to ensure all paths produce
compatible outputs.

Uses contracts/validation.py for JSON Schema 2020-12 compliance.
"""

from typing import Dict, Any, List
from ...engine.module_interface import ExecutableModule, ModuleInput, ModuleOutput, ModuleExecutionError
from contracts.validation import (
    validate_against_schema,
    format_errors_for_display,
    ValidationResult
)
from jsonschema.exceptions import SchemaError


class ValidateModule(ExecutableModule):
    """
    Module for validating state values against JSON Schema.

    This module is typically auto-generated by the execution groups flattener
    to ensure all execution paths produce compatible outputs. It can also
    be used manually in workflows for data validation.

    Uses JSON Schema 2020-12 via contracts/validation.py for consistency
    with client-side validation (WebUI uses Ajv with same draft).

    Inputs:
        - schema: JSON Schema to validate against
        - state_keys: List of state keys to validate (extracted from state and validated as object)
        - strict: Whether to fail on validation errors (default: False)

    Outputs:
        - valid: Boolean indicating validation passed
        - errors: List of validation errors (empty if valid)

    Raises:
        ModuleExecutionError: If validation fails and strict=True
    """

    @property
    def module_id(self) -> str:
        return "io.validate"

    @property
    def inputs(self) -> List[ModuleInput]:
        return [
            ModuleInput(
                name="schema",
                type="object",
                required=True,
                description="JSON Schema to validate against"
            ),
            ModuleInput(
                name="state_keys",
                type="array",
                required=True,
                description="List of state keys to extract and validate"
            ),
            ModuleInput(
                name="strict",
                type="boolean",
                required=False,
                default=False,
                description="Whether to fail on validation errors (default: False, just log warnings)"
            ),
            ModuleInput(
                name="error_message",
                type="string",
                required=False,
                default=None,
                description="Custom error message prefix for validation failures"
            )
        ]

    @property
    def outputs(self) -> List[ModuleOutput]:
        return [
            ModuleOutput(
                name="valid",
                type="boolean",
                description="Whether validation passed"
            ),
            ModuleOutput(
                name="errors",
                type="array",
                description="List of validation error messages (empty if valid)"
            )
        ]

    def execute(self, inputs: Dict[str, Any], context) -> Dict[str, Any]:
        """Execute JSON Schema validation on state values."""
        try:
            schema = inputs["schema"]
            state_keys = inputs["state_keys"]
            strict = self.get_input_value(inputs, "strict")
            error_message = self.get_input_value(inputs, "error_message")

            # Extract values from state
            data = {}
            for key in state_keys:
                if hasattr(context, 'state') and key in context.state:
                    data[key] = context.state[key]
                elif hasattr(context, 'get_state_value'):
                    data[key] = context.get_state_value(key)
                else:
                    # Key not found in state - include as None
                    data[key] = None

            # Perform validation using shared contract
            result: ValidationResult = validate_against_schema(data, schema)

            # Format errors for output
            error_strings = format_errors_for_display(result.errors)

            # Log result
            if result.valid:
                context.logger.debug(
                    f"✓ Validation passed for keys: {state_keys}"
                )
            else:
                log_msg = f"Validation failed for keys {state_keys}: {error_strings}"
                if strict:
                    context.logger.error(log_msg)
                    prefix = error_message or "State validation failed"
                    raise ModuleExecutionError(
                        self.module_id,
                        f"{prefix}: {'; '.join(error_strings)}",
                        None
                    )
                else:
                    context.logger.warning(log_msg)

            return {
                "valid": result.valid,
                "errors": error_strings
            }

        except ModuleExecutionError:
            raise
        except SchemaError as e:
            raise ModuleExecutionError(
                self.module_id,
                f"Invalid JSON Schema: {e.message}",
                e
            )
        except Exception as e:
            raise ModuleExecutionError(
                self.module_id,
                f"Unexpected error during validation: {str(e)}",
                e
            )
